name: Azure Login Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     
      - name: Test1
        id: test1
        run: |
          h=$(az --version)

          echo "::set-output name=h::$h"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Checkout code
        uses: actions/checkout@v3

    # When running on self-hosted GitHub Actions runners,
    # NodeJS must be previously installed with the version specified in the action.yml.
      - uses: actions/setup-node@v2
        with:
         node-version: '20'
    

      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
  
      - name: Terraform init
        id: init
        run: terraform init
