name: Azure Login Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
   #formats your Terraform configuration files to a canonical style, ensuring readability and consistency
      - name: Terraform Format
        run: terraform fmt
   #linting terraform 
      - name: Terraform lint
        run: tflint 
   
  # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false
  # On push to "master", build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        run: terraform apply -auto-approve
