name: Azure Login Example....

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     
      - name: Test1
        id: test1
        run: |
          h=$(az --version)

          echo "::set-output name=h::$h"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Checkout code
        uses: actions/checkout@v3

    # When running on self-hosted GitHub Actions runners,
    # NodeJS must be previously installed with the version specified in the action.yml.
      - uses: actions/setup-node@v2
        with:
         node-version: '20'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "^1.3.7"
          terraform_wrapper: false
      - name: Terraform Format
        run: terraform fmt

      - name: Terraform init
        run: terraform init
  # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false
  # On push to "master", build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        run: terraform apply -auto-approve
  
     
