name: Run Azure Login with the Service Principal secret
on: [push]

jobs:
  azurelogin:
    runs-on: self-hosted
    steps:
    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3


    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
   #formats your Terraform configuration files to a canonical style, ensuring readability and consistency
    - name: Terraform Format
      run: terraform fmt
   #linting terraform 
    - name: Terraform lint
      run: tflint 
   
  # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
  # On push to "master", build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      run: terraform apply -auto-approve
